##
## lis-genefunction keys
##

Ontology.key_name=name
OntologyTerm.key_identifier=identifier
TOTerm.key_name=name
OntologyAnnotation.key_subject_term=subject,ontologyTerm
DataSource.key_name=name
DataSet.key_name=name
Publication.key_doi=doi
Author.key_name=name

## Annotatable
Gene.key_primaryidentifier=primaryIdentifier
